### ISSUE TITLE
Editor tabs overlap

### ISSUE THREAD

**Issue by InvertedGames-Dev** [TheHerobrine/DarkerNodes#10]
The tabs seem to be too long, which makes them overlap with the tabs next to it
![image](https://user-images.githubusercontent.com/32015329/102154388-31d01080-3ec9-11eb-9398-3996343794f0.png)

![image](https://user-images.githubusercontent.com/32015329/102154398-398fb500-3ec9-11eb-98cc-f53fdca2d52b.png)

**Comment by TheHerobrine** [comment]
Fixed! Will be available in 1.1

![image](https://user-images.githubusercontent.com/4563971/102239754-7bcfeb00-3ef7-11eb-9b7c-1fbc7fd045e5.png)

![image](https://user-images.githubusercontent.com/4563971/102239789-81c5cc00-3ef7-11eb-950f-204a4e7992d1.png)

**Comment by TheHerobrine** [comment]
Available. If you're on 4.26, wait for the 1.2 update (I let a debug thing on the 4.26 1.1 update... cf https://github.com/TheHerobrine/DarkerNodes/issues/21)
