### ISSUE TITLE
Make node header color customizable

### ISSUE THREAD

**Issue by TheHerobrine** [TheHerobrine/DarkerNodes#102]
Some people would like the node color header to be brighter

**Comment by TheHerobrine** [comment]
Added two settings to change opacity and saturation:
![image](https://user-images.githubusercontent.com/4563971/105613928-fbd65400-5dc5-11eb-8eee-1f08259299ad.png)

**Comment by schmigel** [comment]
This option doesn't appear on UE 4.26 and UE4.27 (source build). Clicking Fix Missing Elements doesnt fix it.
