### ISSUE TITLE
Scroll bars have inverted color language - often leading to misclicking

### ISSUE THREAD

**Issue by THEAETIK** [TheHerobrine/DarkerNodes#104]
Most applications have the scroll bar handle brighter than the rest of the context. In Darker Nodes, this color language is reversed.

![image](https://user-images.githubusercontent.com/34952563/104965744-642fca80-59ad-11eb-820d-078ab88e6248.png)

**Comment by TheHerobrine** [comment]
Yes, it's for the scrollbar to be less distracting. Though, if you prefer the white scrollbar, there's an option for this, you just have to disable this and restart the editor:
![image](https://user-images.githubusercontent.com/4563971/104966399-11700600-59e1-11eb-907a-f462ff0993df.png)

If what you meant was that you'd like to choose the color of the scrollbar, just tell me, and I'll make it happen in the next update 😉.

**Comment by THEAETIK** [comment]
Ah yeah, I missed that option. I see what you mean by distracting, I suppose a custom color would be nice yeah, I'd use that.

**Comment by TheHerobrine** [comment]
Noted, it's going to be a new feature!

**Comment by TheHerobrine** [comment]
You can now change the color of the scrollbar:
![image](https://user-images.githubusercontent.com/4563971/105606674-12b38100-5d9b-11eb-89b5-0e87499dd06b.png)
