### ISSUE TITLE
Decimal fields have unnecessary spacing, clipping and limiting visible numbers

### ISSUE THREAD

**Issue by THEAETIK** [TheHerobrine/DarkerNodes#105]
![image](https://user-images.githubusercontent.com/34952563/104966076-0fd91a80-59ae-11eb-98c8-a6819cd668d2.png)

**Comment by TheHerobrine** [comment]
Hum, padding for those fields are really weird, but I guess I could just reduce the horizontal padding... I'll do this for the next update!

**Comment by TheHerobrine** [comment]
I think this should be good 🤔... (I gained 8px)
![image](https://user-images.githubusercontent.com/4563971/105606400-6ae98380-5d99-11eb-8685-87eb89f3a822.png)
