### ISSUE TITLE
Snap Settings Spacing Lines don't fit

### ISSUE THREAD

**Issue by CascadeNP** [TheHerobrine/DarkerNodes#112]
![IMG_20210123_133025.jpg](https://user-images.githubusercontent.com/65467012/105578277-3bc61880-5d7f-11eb-951a-4d0146fb1b0d.jpg)

**Comment by TheHerobrine** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/4563971/105608622-45ae4280-5da4-11eb-9b24-91058c345280.png)
