### ISSUE TITLE
World Outliner Padding is hiding Content

### ISSUE THREAD

**Issue by CascadeNP** [TheHerobrine/DarkerNodes#118]
![WorldOutliner](https://user-images.githubusercontent.com/65467012/105727855-ca779880-5f2b-11eb-882f-1e8175881d9c.PNG)

**Comment by TheHerobrine** [comment]
@CascadeNP That's weird, I don't have this 🤔... Is this on 4.26 ? Could you try to do this and tell me is that fix it ?
https://github.com/TheHerobrine/DarkerNodes/wiki/FAQ#some-elements-are-invisible--search-box-are-glitchy-or-unreadable

![image](https://user-images.githubusercontent.com/4563971/105728140-19bdc900-5f2c-11eb-8d85-16a678d1d7dc.png)

**Comment by CascadeNP** [comment]
Oh sorry, it was just a weird bug. I reinstalled UE and its fixed now! Thanks anyways!
