### ISSUE TITLE
Make tab height smaller

### ISSUE THREAD

**Issue by CascadeNP** [TheHerobrine/DarkerNodes#119]

**Comment by TheHerobrine** [comment]
@CascadeNP Could you please make a screen for me to understand what tab you are referring to 😅 ?

**Comment by CascadeNP** [comment]
![TabHeight](https://user-images.githubusercontent.com/65467012/105729711-c9e00180-5f2d-11eb-8a36-e88c88dab4bd.PNG)

Is there a way to make this smaller, or is it hardcoded? It could save some space

**Comment by TheHerobrine** [comment]
That's the kind of thing that is likely hard coded, but I'll have a look 😉

**Comment by TheHerobrine** [comment]
I admit I spent a fair amount of time searching how I could do this, but it seems that I can't really change it... Even when giving a negative padding it doesn't change anything. Only horizontal padding can be changed, and I feel like it's too narrowed to reduce it 😕.

I'll close this, sorry...
