### ISSUE TITLE
VariantSets

### ISSUE THREAD

**Issue by zjrl** [TheHerobrine/DarkerNodes#122]
![image](https://user-images.githubusercontent.com/69996552/105958039-0c801600-60b5-11eb-9a0d-5625fad3e0b4.png)

**Comment by TheHerobrine** [comment]
Thank you very much for spoting this! Out of curiosity, how can I access such panel?

**Comment by zjrl** [comment]
![HI](https://user-images.githubusercontent.com/69996552/106152327-38fb6700-6175-11eb-88f6-c1b71db6ee96.jpg)

**Comment by TheHerobrine** [comment]
Ok, seems like this variant manager plugin is not compatible with margins wince it forces the height of the input boxes.
I've added a "None" margin option in the settings to make it work, but it will affect every button/textbox:

![image](https://user-images.githubusercontent.com/4563971/107126047-c80f2a00-68ad-11eb-845a-ef694d6f5cb9.png)

![image](https://user-images.githubusercontent.com/4563971/107126054-dc532700-68ad-11eb-8b48-1517ad187323.png)
