### ISSUE TITLE
Start Menu is broken

### ISSUE THREAD

**Issue by CascadeNP** [TheHerobrine/DarkerNodes#124]
![BuggedOutStart](https://user-images.githubusercontent.com/65467012/106298657-71be3d80-6254-11eb-966f-426e74a75cd4.PNG)

Bugs: 

- Backround Black
- Logo looks wrong
- Buttons are bugged out 
- Hovering over clickable areas causes the backround to remain white

Happens when EabledByDefault is true.

**Comment by TheHerobrine** [comment]
Oh! I never though that the "EnabledByDefault" would load the plugin even on the start menu!

I'll look into that, thank you for spotting it.

**Comment by CascadeNP** [comment]
I don't even know why it's broken now. A couple of days ago it worked and it looked pretty good

**Comment by TheHerobrine** [comment]
That's really weird...

Sadly, plugins are not made to have a single configuration for every project. For now, you could c/c your configuration that you can find here: https://github.com/TheHerobrine/DarkerNodes/wiki/FAQ#where-to-find-my-saved-configuration-of-darkernodes

But I'll create an issue to investigate the possibility to make a global configuration, I may have an idea 🤔

**Comment by CascadeNP** [comment]
Oh, alright. Thanks a lot!

**Comment by TheHerobrine** [comment]
Ok, so I just disable the plugin for the startup menu since I didn't find any way to fix the problem 🤔... Anyway, I don't think people spend a lot of time on it 😅...
