### ISSUE TITLE
Invisible Texture!

### ISSUE THREAD

**Issue by raijoking** [TheHerobrine/DarkerNodes#126]
![111](https://user-images.githubusercontent.com/21275721/106342538-54cd4d00-62dc-11eb-976a-682799298eed.PNG)
Is this bug or got miss with the setting?

**Comment by CascadeNP** [comment]
Looks kinda neat tho. Would like to see that as an option

**Comment by TheHerobrine** [comment]
Sorry for that... Try to go on "Edit/Editor preferences/Darker Nodes", and click on "Fix missing elements" ;)

**Comment by TheHerobrine** [comment]
@CascadeNP you'd like that 🤔... I can make this bug a feature, yes 😅

**Comment by CascadeNP** [comment]
Would be great, thanks!

**Comment by raijoking** [comment]
> 
> 
> Sorry for that... Try to go on "Edit/Editor preferences/Darker Nodes", and click on "Fix missing elements" ;)

Thank you :) you can closed this issued <3 it's already fixed
