### ISSUE TITLE
UMG Buttons turn white entirely in non shipping builds sometimes

### ISSUE THREAD

**Issue by MightyyDan** [TheHerobrine/DarkerNodes#127]
UMG buttons will turn white on hover.    This only happens in preview mode though playing in standalone window or a shipping build does not have this issue.

On the video shown, I have not edited the button It's just the default umg button prefab... the issue disapears when darkernodes is disabled so I think It's isolated to an issue with the plugin somewhere idk?

I have also seen this on checkboxes but I cannot reproduce it
https://streamable.com/qcqi2a

**Comment by TheHerobrine** [comment]
Hum, I though this was fix with this https://github.com/TheHerobrine/DarkerNodes/issues/80, but it seems like it's not quite 100% fixed 🤔... I'll look into it, thanks for the report!

**Comment by MightyyDan** [comment]
It's very random and can't always reproduce it.   I've updated to latest version and running 4.26.        Could just be an unreal engine bug but maybe worth checking anyways as I had it before with checkboxes a few weeks ago.

**Comment by TheHerobrine** [comment]
![image](https://user-images.githubusercontent.com/4563971/107126920-fcd1b000-68b2-11eb-90a2-fa1768a3494b.png)

**Comment by TheHerobrine** [comment]
Ok, it was (again) the weird behavior of the garbage collector. It's now fixed!

**Comment by trdwll** [comment]
I thought it was the way I set up some of my buttons. Glad to know it was the plugin and thanks for fixing it. 😅
