### ISSUE TITLE
Add some settings to customize bp nodes opacity

### ISSUE THREAD

**Issue by TheHerobrine** [TheHerobrine/DarkerNodes#128]
Some people would like the nodes to be opaque

**Comment by Saiodin** [comment]
Awesome, thanks. I usually have my nodes setup in a very specific way that wouldn't make it a problem to have the lines disappear behind nodes. But if you're making it a slider like many other options, maybe 90% opaque is already good. I personally just dislike seeing the grid through the node, but usually don't wanna turn off the grid 100%.

**Comment by TheHerobrine** [comment]
Done, the unchecking of "Use Blueprint Grid" will also disable UMG grid:
![image](https://user-images.githubusercontent.com/4563971/107127549-255ba900-68b7-11eb-8263-b14becb7e8ce.png)

**Comment by TheHerobrine** [comment]
Ok, it's done! You'll be able to make whatever color you like, with whatever transparency!
![image](https://user-images.githubusercontent.com/4563971/107149507-4aa0f380-6959-11eb-89df-bae2fc81a422.png)

**Comment by Saiodin** [comment]
Amazing, very much appreciated!
