### ISSUE TITLE
Disable grid lines on Widget blueprint

### ISSUE THREAD

**Issue by TheHerobrine** [TheHerobrine/DarkerNodes#129]
Seems like widget blueprint lines doesn't disappear with the "disable blueprint lines" options

**Comment by TheHerobrine** [comment]
Done, the unchecking of "Use Blueprint Grid" will also disable UMG grid:
![image](https://user-images.githubusercontent.com/4563971/107127549-255ba900-68b7-11eb-8263-b14becb7e8ce.png)

**Comment by Saiodin** [comment]
If it's possible to separate these UMG lines from the usual BP lines I think that it's worth separating them. The lines are a great help for designing UI.

**Comment by TheHerobrine** [comment]
Hum, you're right... I'll make two checkboxes! (but it won't be possible to disable only the UMG lines)

**Comment by TheHerobrine** [comment]
Done! It will be available for 2.6 😉
![image](https://user-images.githubusercontent.com/4563971/107514011-57b42180-6ba9-11eb-840a-eea574bca34c.png)
