### ISSUE TITLE
4.24 have no colors in graph header

### ISSUE THREAD

**Issue by nepyneptune** [TheHerobrine/DarkerNodes#132]
at 4.26: 
![image](https://user-images.githubusercontent.com/68301257/107249129-16eec800-6a44-11eb-8817-c5febc36df6d.png)
Main project at 4.24.1
![image](https://user-images.githubusercontent.com/68301257/107249152-20783000-6a44-11eb-8e2d-cd70bda9a492.png)
I would like to change BP node header saturation and opacity, both is not work on 4.24 version.
(tried check fix missing elements)

**Comment by TheHerobrine** [comment]
Hum, ok I see...

The problem with 4.24 is that the blueprint header are weirdly implemented.

- I can make a switch to the last behavior: https://github.com/TheHerobrine/DarkerNodes/issues/91
Which mean there will be colors, but the header won't take the whole space.

- Or I can do both: the background will take the whole space, but not the color.

- Or I can do a gradient from color to gray background.

There's no silver bullet for this... What solution would you prefer?

**Comment by nepyneptune** [comment]
> Hum, ok I see...
> 
> The problem with 4.24 is that the blueprint header are weirdly implemented.
> 
> * I can make a switch to the last behavior: #91
>   Which mean there will be colors, but the header won't take the whole space.
> * Or I can do both: the background will take the whole space, but not the color.
> * Or I can do a gradient from color to gray background.
> 
> There's no silver bullet for this... What solution would you prefer?

Ohh.. i didnt knoe its bug from engine, thought this missed from just plugin if that so.. Well i should switch to 4.26 one. Thank you for reply

**Comment by TheHerobrine** [comment]
> Well i should switch to 4.26 one.

Yeah, that's the easiest solution 🤔 (it will work on 4.25 aswell). I'm closing this 😉
