### ISSUE TITLE
uhh Updated, two days later Editor crashed and the this... happens with most text

### ISSUE THREAD

**Issue by stardast132** [TheHerobrine/DarkerNodes#134]
![image](https://user-images.githubusercontent.com/75868062/107562668-be374080-6ba5-11eb-8a2f-6beec38ef615.png)

**Comment by TheHerobrine** [comment]
Could you try to go in `Edit/Editor Preferences/Darker Nodes` and click on "Fix Missing Elements"?

**Comment by TheHerobrine** [comment]
I really need to autodetect when materials are wrong...

**Comment by TheHerobrine** [comment]
(soooo, did it fixed it?)

**Comment by stardast132** [comment]
Yes fixed everything. Thank you
