### ISSUE TITLE
4.23 Support

### ISSUE THREAD

**Issue by DiegoECamachoIBI** [TheHerobrine/DarkerNodes#137]
Is there a way to get 4.23 Support for the plugin? I love the plugin and would love to use it daily, but most of our projects are currently in 4.23. and It hurts me emotionally to have to use the old UI when this one is so much better.

**Comment by TheHerobrine** [comment]
@DiegoECamachoIBI Thank you very much 🙂

Hum, you should be able to make it work on 4.23 by copy/pasting the plugin in
`D:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace\DarkerNodes`
to your project plugins folder (create it if it does not exist)
`YourProjects\Plugins`

This should work! If there's an error, just tell me and I'll have a look to see if there's a quick fix 😉

**Comment by DiegoECamachoIBI** [comment]
@TheHerobrine Thanks for the quick reply,
I was originally doing it through engine plugins and It would fail compile. I've moved the plugin to the projects plugins folder and the project launches and get to around 95% before crashing with this error 
![image](https://user-images.githubusercontent.com/77292501/108776543-8bd7fc80-7530-11eb-84e9-c5895d496555.png)

I can pass the full crash report, if this isn't enough.

**Comment by TheHerobrine** [comment]
Hum, I see... I'll try to find a fix, but 4.23 won't be "officially" supported though 😅.

**Comment by DiegoECamachoIBI** [comment]
Thanks for the help, I'll be praying for a fix, but it's not the end of the world if there's no fix. Let me know if I can help test anything on my config.

**Comment by TheHerobrine** [comment]
Ok, I made it work on 4.23, I'll push this version to the marketplace for people to insall it easily 😉 !

![image](https://user-images.githubusercontent.com/4563971/109311393-16c53980-7846-11eb-8c9b-fb074529a8a9.png)

**Comment by TheHerobrine** [comment]
Ok, seems like there's still a restriction on the engines...
![image](https://user-images.githubusercontent.com/4563971/109312130-f8137280-7846-11eb-8aef-a144d36af97a.png)

To make it work, do the same things you did, but replace the `Plugins/Darker Nodes/Content` folder by this:
[Content.zip](https://github.com/TheHerobrine/DarkerNodes/files/6050166/Content.zip)

**Comment by DiegoECamachoIBI** [comment]
That's a strange restriction on epics side, but it works perfectly for me now!, thank you very much for the help.

**Comment by TheHerobrine** [comment]
Nice 😄 ! So I'm closing the issue !
(If you have a little time, that would be very cool if you left a review on the product page 🙂)
