### ISSUE TITLE
Add option to set color of variable nodes

### ISSUE THREAD

**Issue by Gooner44** [TheHerobrine/DarkerNodes#18]
The brightly colored pills for variables make finding things in a large blueprint nice and easy. The new look is great, but you lose that pop-out color you get with the default theme. I'd like to see an option to make those nodes the same flat color as their type with white/black text.

**Comment by TheHerobrine** [comment]
Thanks for the suggestion 🙂! I think it's a duplicate of https://github.com/TheHerobrine/DarkerNodes/issues/14, if I'm understanding it right?

**Comment by TheHerobrine** [comment]
I close this because #14 solve this 😉
