### ISSUE TITLE
some text is black

### ISSUE THREAD

**Issue by tiantianaixuexi** [TheHerobrine/DarkerNodes#19]
![1](https://user-images.githubusercontent.com/31758095/102322933-c9f9f280-3fba-11eb-804d-46c69f4fa4f2.png)
![2](https://user-images.githubusercontent.com/31758095/102322940-cbc3b600-3fba-11eb-854b-e2d2174edbda.png)

**Comment by TheHerobrine** [comment]
Thank you for spotting it! It has already been addressed and the update is being approved, it should be available in the next 24h 😉

https://github.com/TheHerobrine/DarkerNodes/issues/3

**Comment by TheHerobrine** [comment]
Fixed on 1.1 with https://github.com/TheHerobrine/DarkerNodes/issues/3
