### ISSUE TITLE
Child modal opens EVERYTIME I open my project, please make it stop!

### ISSUE THREAD

**Issue by jamesmandrews** [TheHerobrine/DarkerNodes#194]
Everytime I open my 5.5 project I get you advertising modal. It's really annoying, please make it stop.

**Comment by hugoattal** [comment]
Shit, this is definitely not supposed to happen... So sorry, I'm looking into it right now!

(You should get it ONCE per update and that's all)

**Comment by hugoattal** [comment]
Continue here: https://github.com/hugoattal/ElectronicNodes/issues/95

**Comment by jamesmandrews** [comment]
This issue is now resolved, thank you.
