### ISSUE TITLE
Timeline buttons change

### ISSUE THREAD

**Issue by Thovex** [TheHerobrine/DarkerNodes#27]
![image](https://user-images.githubusercontent.com/9029361/102490120-b1e3ab00-406e-11eb-9c8f-e04cd1fe2d6b.png)

Pretty dark buttons right now : D

**Comment by TheHerobrine** [comment]
Oops, forgot to turn them white... Sorry for that, thank you for spotting it, this will be fixed on the next update!

**Comment by TheHerobrine** [comment]
Fixed ready for 1.3!
![image](https://user-images.githubusercontent.com/4563971/102504611-553dbb80-4081-11eb-96cc-5718e0bbe5b8.png)

**Comment by TheHerobrine** [comment]
Update available!
