### ISSUE TITLE
Session Frontend profiler buttons turn dark

### ISSUE THREAD

**Issue by Thovex** [TheHerobrine/DarkerNodes#28]
![image](https://user-images.githubusercontent.com/9029361/102490841-b0ff4900-406f-11eb-8007-3627f11fc4cc.png)

Hope you don't mind the spam! But I noticed these buttons go dark as well and thus 'hiding' the text in the Session Frontend.

**Comment by TheHerobrine** [comment]
> Hope you don't mind the spam!

@Thovex If there are bugs it's 100% my fault 😕...

> But I noticed these buttons go dark as well and thus 'hiding' the text in the Session Frontend.

Could you tell me how to get on that screen from a blank project? I'm not familiar with it...

**Comment by Thovex** [comment]
Yes, it is Windows -> Developer Tools -> Session Frontend.

Then you want to click "data capture" while playing playing in-editor. After a few seconds just press it again, it asks to save the file, you want to save it and then load it.

Once it has loaded you can basically revisit what happened during each frame. If you then click any of the events on the bottom it creates a load of default UE4 buttons with some text representing functions being called and stuff, such as this: 
![image](https://user-images.githubusercontent.com/9029361/102491532-a0030780-4070-11eb-975d-7abfbdd4be1d.png)

**Comment by Thovex** [comment]
https://docs.unrealengine.com/en-US/TestingAndOptimization/PerformanceAndProfiling/Profiler/index.html

This is the official documentation on the profiler, also no worries :), thanks for the quick updates & support.

**Comment by TheHerobrine** [comment]
Fixed, will be available on 1.3 update!
![image](https://user-images.githubusercontent.com/4563971/102509477-e06d8000-4086-11eb-91cf-e8ad47c96aee.png)

**Comment by TheHerobrine** [comment]
Update available!
