### ISSUE TITLE
Black test In some text input fields

### ISSUE THREAD

**Issue by Arixsus** [TheHerobrine/DarkerNodes#3]
![image](https://user-images.githubusercontent.com/4563971/102234063-31e40680-3ef1-11eb-8e5e-7ff9d0d5863e.png)

Its not on all text input fields. Nor all blueprints but sometimes it can really be hard to see.

**Comment by TheHerobrine** [comment]
Thank you for the report!

Yes, I may have forgotten some, but others hard black hard-coded and can't be change...
I'll list the ones that I can't change and change the ones I can!

**Comment by TheHerobrine** [comment]
Another place:
![image](https://user-images.githubusercontent.com/4563971/102233933-0f51ed80-3ef1-11eb-881a-04563f85e98b.png)

**Comment by SUPRVLLAN** [comment]
+1 folllowing!

**Comment by TheHerobrine** [comment]
![image](https://user-images.githubusercontent.com/4563971/102249144-51cff600-3f02-11eb-8381-5ff3fe3fe659.png)
![image](https://user-images.githubusercontent.com/4563971/102249205-6613f300-3f02-11eb-9a3d-746582b32e6d.png)
![image](https://user-images.githubusercontent.com/4563971/102249119-4bda1500-3f02-11eb-9890-b1f293284383.png)

Wow, didn't expect that, but I actually managed to fixed everything in one try 😮!

So fixed, will be available on 1.1 🙂

**Comment by SUPRVLLAN** [comment]
Awesome, thanks a lot!

**Comment by TheHerobrine** [comment]
Available. If you're on 4.26, wait for the 1.2 update (I let a debug thing on the 4.26 1.1 update... cf https://github.com/TheHerobrine/DarkerNodes/issues/21)

**Comment by SUPRVLLAN** [comment]
Thank you for addressing this so quickly!
