### ISSUE TITLE
Var Input Black Text while typing the value.

### ISSUE THREAD

**Issue by raijoking** [TheHerobrine/DarkerNodes#35]
![bug](https://user-images.githubusercontent.com/21275721/102681341-a1147000-41fb-11eb-9193-f8c31bd50cb9.PNG)

When I start to type any value from the var it goes to black text but after you press enter (to refresh) the var the text will going back to white again. It only happens during typing the input value on it

**Comment by TheHerobrine** [comment]
Ok, so it appears that this color is based on the GreyLight, which is the same from the arrows.

So I just lighten up a bit the GreyLight color:
![image](https://user-images.githubusercontent.com/4563971/102693072-29a10980-4218-11eb-9bfc-b6bad9699942.png)

Btw, it seems that you changed the GreyLight value to something darker, didn't you?
