### ISSUE TITLE
Sequencer

### ISSUE THREAD

**Issue by zjrl** [TheHerobrine/DarkerNodes#38]
![DNP](https://user-images.githubusercontent.com/69996552/102731830-e2c82680-4373-11eb-9b95-4d5e37ac4a19.jpg)
你好，请问Sequencer曲线的背景颜色如何设置？或者曲线的拉杆的颜色如何设置？
Hi, how do the background colors for the Sequencer curve set?Or how to set the color of the curved rod?

**Comment by TheHerobrine** [comment]
Well, the white background appears to be a bug, sorry for that, I'll solve this as soon as possible!

I don't know if you can change the color of the curve, I'll check that.

**Comment by TheHerobrine** [comment]
Fixed! I'll probably change a bit the grid lines color though...

![image](https://user-images.githubusercontent.com/4563971/102886143-dec00580-4454-11eb-89af-cf6679cc4d66.png)

**Comment by TheHerobrine** [comment]
Might be hard-coded 😕...
![image](https://user-images.githubusercontent.com/4563971/102886633-c00e3e80-4455-11eb-9a88-479024e68a6e.png)

from `Editor/UnrealEd/Public/SCurveEditor.h` line 196
