### ISSUE TITLE
custom

### ISSUE THREAD

**Issue by zjrl** [TheHerobrine/DarkerNodes#40]
自定义颜色重启后无法保存正确设置内容.
The correct Settings could not be saved after a custom color restart

https://user-images.githubusercontent.com/69996552/102843909-39e9fc00-4445-11eb-94d3-da45f41ac600.mp4

**Comment by TheHerobrine** [comment]
Yes, sorry for this 😕... It's actually the same as https://github.com/TheHerobrine/DarkerNodes/issues/39

The light and temperature modify the customized greys, so while I'll fix that, you can set the Ligth to Darker and the temperature to Normal.

This will be fixed and available in a couple of days.
