### ISSUE TITLE
Make the small icons properly

### ISSUE THREAD

**Issue by TheHerobrine** [TheHerobrine/DarkerNodes#41]
I did it the lazy way by resizing the big icons. It was a bad idea 😕...

**Comment by TheHerobrine** [comment]
Also, add an option to have different color for each icon

**Comment by TheHerobrine** [comment]
Before:
![icon_toolbar_genericfinder_40px](https://user-images.githubusercontent.com/4563971/103465938-9f40c580-4d40-11eb-8552-541ba6dcb28d.png)![icon_SaveAsset_40x](https://user-images.githubusercontent.com/4563971/103465947-b4b5ef80-4d40-11eb-87a2-2edf336bbf6f.png)![icon_Blueprint_Find_40px](https://user-images.githubusercontent.com/4563971/103465942-a962c400-4d40-11eb-9ca4-9d3e16e5c8ce.png)

After:
![icon_toolbar_genericfinder_40px](https://user-images.githubusercontent.com/4563971/103465998-1b3b0d80-4d41-11eb-8f8d-0a01785c27b4.png)![icon_SaveAsset_40x](https://user-images.githubusercontent.com/4563971/103466015-4aea1580-4d41-11eb-8707-88a12a69b585.png)![icon_Blueprint_Find_40px](https://user-images.githubusercontent.com/4563971/103466016-4cb3d900-4d41-11eb-863d-4d8ef926ac47.png)

(You might need github in dark mode to actually see the icons)

**Comment by TheHerobrine** [comment]
Pfew, everything's done!
![image](https://user-images.githubusercontent.com/4563971/103466965-4bd37500-4d4a-11eb-9c8c-b68012378c61.png)

**Comment by TheHerobrine** [comment]
Before:
![image](https://user-images.githubusercontent.com/4563971/103467163-8c33f280-4d4c-11eb-83f6-05f3065f1940.png)

After:
![image](https://user-images.githubusercontent.com/4563971/103467229-4297d780-4d4d-11eb-8b1d-1bb989502af8.png)

**Comment by TheHerobrine** [comment]
Ready for 1.6!

**Comment by raijoking** [comment]
How to used this small icon? I already updated to 1.6 I only can get the Before Preview not the After preview :)

**Comment by TheHerobrine** [comment]
@raijoking It's an engine configuration, you need to go to `Edit/Editor Preferences/Appearance` and check this 😉

![image](https://user-images.githubusercontent.com/4563971/103765265-30ec5380-501d-11eb-9b20-6a894fd5daa3.png)
