### ISSUE TITLE
Level Icons have incorrect scale

### ISSUE THREAD

**Issue by GoVRCenter** [TheHerobrine/DarkerNodes#42]
![image](https://user-images.githubusercontent.com/7493656/102921574-9b689580-445a-11eb-92b2-034230919085.png)

Icons are squashed, also there's no VR preview and mode icons.
![image](https://user-images.githubusercontent.com/7493656/102921680-c3f08f80-445a-11eb-9c22-35ea0b9253c0.png)

**Comment by TheHerobrine** [comment]
@GoVRCenter Sorry for this... It looks a lot like this issue: https://github.com/TheHerobrine/DarkerNodes/issues/30

Did you update your plugin to 1.4 (you can see its version under Edit/Plugins)?

On the VR icon, you're right, I forgot to do it... I'm creating an issue for it!
