### ISSUE TITLE
Add icons to the theme (level icons + VR icon)

### ISSUE THREAD

**Issue by TheHerobrine** [TheHerobrine/DarkerNodes#43]
I should update those icons:

- [x] VR Buttons
- [x] Material Editor
- [x] Mesh Editor
- [x] Animation Editor

![image](https://user-images.githubusercontent.com/4563971/102922110-c91b0200-448d-11eb-9abb-f862b01f7abf.png)
![image](https://user-images.githubusercontent.com/4563971/103469546-6c112d00-4d66-11eb-89c1-f90b1f58284c.png)
![image](https://user-images.githubusercontent.com/4563971/103469548-703d4a80-4d66-11eb-84b5-e68771ad6b7c.png)

<details>
  <summary>Done</summary>

![image](https://user-images.githubusercontent.com/4563971/102922121-cb7d5c00-448d-11eb-9840-297016ea826b.png)
![image](https://user-images.githubusercontent.com/4563971/103463947-71ec1b80-4d30-11eb-8067-7b10e18549d9.png)
![image](https://user-images.githubusercontent.com/4563971/103463929-554fe380-4d30-11eb-9af6-63ffd2573eec.png)
![image](https://user-images.githubusercontent.com/4563971/103463932-5aad2e00-4d30-11eb-9226-dae60db91bbc.png)
![image](https://user-images.githubusercontent.com/4563971/103463931-57b23d80-4d30-11eb-80d7-10dec8dbe3bf.png)
</details>

**Comment by GoVRCenter** [comment]
The VR mode too please! Thanks so much, loving the plugin. 
![image](https://user-images.githubusercontent.com/7493656/103231802-b62d8500-4906-11eb-9b2c-97e1321bbb89.png)

**Comment by TheHerobrine** [comment]
![image](https://user-images.githubusercontent.com/4563971/103463929-554fe380-4d30-11eb-9af6-63ffd2573eec.png)
![image](https://user-images.githubusercontent.com/4563971/103463931-57b23d80-4d30-11eb-80d7-10dec8dbe3bf.png)
![image](https://user-images.githubusercontent.com/4563971/103463932-5aad2e00-4d30-11eb-9226-dae60db91bbc.png)

**Comment by TheHerobrine** [comment]
- [x] Play in VR
- [x] VR Mode

**Comment by TheHerobrine** [comment]
It's getting somewhere!
![image](https://user-images.githubusercontent.com/4563971/103478408-c641da80-4dc6-11eb-9afa-6ce890937ed2.png)

**Comment by TheHerobrine** [comment]
The animation editor:
![image](https://user-images.githubusercontent.com/4563971/103481217-c7c8ce00-4dd9-11eb-9f26-0470ca48a220.png)

**Comment by TheHerobrine** [comment]
I'll do the small ones in another issue for the 1.7, I'm marking this as ready for 1.6.
