### ISSUE TITLE
"Realtime" button text illegible

### ISSUE THREAD

**Issue by deanvaessen** [TheHerobrine/DarkerNodes#45]
A bit tricky to read:
![UE4Editor_GR5sRurmDC](https://user-images.githubusercontent.com/13887261/103001471-5e210800-452d-11eb-8d92-de7490e3bdd3.png)

**Comment by TheHerobrine** [comment]
@deanvaessen How can I see this button 🤔? I'm not familiar with it...

**Comment by deanvaessen** [comment]
That would be right over here: 
![UE4Editor_GR5sRurmDC](https://user-images.githubusercontent.com/13887261/103024502-4444ec80-4550-11eb-
9967-999e0cd04a97.png)

**Comment by deanvaessen** [comment]
That would be right over here:
![BU4XcLrdxM](https://user-images.githubusercontent.com/13887261/103024543-56268f80-4550-11eb-86fa-213f7388c278.png)

**Comment by TheHerobrine** [comment]
Got it 😉! I'll fix this for 1.6!

**Comment by TheHerobrine** [comment]
Sadly, this can't be fixed 😕... The color is hard coded...

![image](https://user-images.githubusercontent.com/4563971/103464480-4408d600-4d34-11eb-92ba-16d970f90164.png)

in `Editor/LevelEditor/Private/SLevelViewportToolBar.cpp` line 274

**Comment by TheHerobrine** [comment]
So I created a wiki page for the hard coded things 😉
https://github.com/TheHerobrine/DarkerNodes/wiki/Engine-hard-coded-values
