### ISSUE TITLE
Tab colour

### ISSUE THREAD

**Issue by deanvaessen** [TheHerobrine/DarkerNodes#51]
It screws with my head a bit that the active tab colour is darker than the unselected tab. In the screenshot below, "Find Results" is darker than the unselected "Compiler Results". 

Instinctively, I'd assume the lighter colour is the one that is active, as the black of "Find Results" tab fades away into the dark "background" colour of the window, and the unselected "Compiler Results" matches the colour of the active panes below them (the search bar & the search results). Hence, I find myself clicking on the wrong tab often.

![UE4Editor_8tDq4QFM37](https://user-images.githubusercontent.com/13887261/103134424-62762e00-46b1-11eb-870f-5c3281faaeb7.png)

![UE4Editor_2R4VFW1x90](https://user-images.githubusercontent.com/13887261/103134816-40ca7600-46b4-11eb-8029-2d015426e82d.png)

Also noteworthy that on the main application window, while the active tab is also darker, the behaviour is different in the sense that the inactive tabs take on the colour of background. This makes the active tab stand out with it's colouring:

![UE4Editor_fiK0wt2W5u](https://user-images.githubusercontent.com/13887261/103134755-c568c480-46b3-11eb-80b4-8234c1b3aec8.png)

Would it be possible to change this behaviour with an option in the config?

**Comment by TheHerobrine** [comment]
Hum, the color of tabs are defined for all the tab, so I can't change only one type of tab... I'll see if I can change the colors of some parts to solve this issue.

**Comment by TheHerobrine** [comment]
Done, it will be ready for 2.0 😄 !

![image](https://user-images.githubusercontent.com/4563971/104029773-b103ec00-51ca-11eb-94d7-53f9936cd106.png)
