### ISSUE TITLE
Statistics panel is pure white

### ISSUE THREAD

**Issue by deanvaessen** [TheHerobrine/DarkerNodes#52]
![UE4Editor_NaFLy7u4um](https://user-images.githubusercontent.com/13887261/103148556-4d58d800-4761-11eb-83ca-b1ca3540872d.png)

**Comment by TheHerobrine** [comment]
@deanvaessen Hum, sorry for this... Would you mind telling me how to get to that panel 🤔?

**Comment by deanvaessen** [comment]
Window -> Statistics ;)

**Comment by TheHerobrine** [comment]
Fixed, ready for 1.6! 
![image](https://user-images.githubusercontent.com/4563971/103468836-b5a94a00-4d5d-11eb-96da-b7d68d19530f.png)

I'll look if I can add a padding though, this table is not easy to read...
