### ISSUE TITLE
Issue with Plugin load order in 4.25 from source

### ISSUE THREAD

**Issue by Altrue** [TheHerobrine/DarkerNodes#53]
Hi,

Just wanted to report that the plugin didn't seem to work very well for me on my 4.25 UE4 built from source.

After comparing it with the launcher's 4.25, and doing some debugging on the plugin, it seems like the content in Editor/EditorStyle/ was being called AFTER Plugins/DarkerNodes/Source/DarkerNodes/, and as is to be expected, undid most of the changes from DarkerNodes.

In DarkerNodes.uplugin, I changed the "LoadingPhase" from "Default" to "PostEngineInit", which has solved the issue for me. It may be a good idea to incorporate this change into the official plugin :)

**Comment by Altrue** [comment]
I'm using a source build in order to be able to build dedicated servers. I haven't changed the engine code, so I don't believe there's anything that might impact the plugin load order on my end.

**Comment by GoVRCenter** [comment]
I am also using a source build of 4.25 and I am not experiencing this issue. Mine is installed to /Engine/Plugins/Marketplace, maybe that makes a difference?

**Comment by TheHerobrine** [comment]
That's weird 🤔... I don't know yet if I'll change the loading phase or if I'll add this to the doc for other people encountering this problem... I'll see what impact a PostEngineInit loading phase can have.

**Comment by Altrue** [comment]
Maybe it's a weird legacy thing that I have going on, or maybe by recompiling the full engine it'll go away. I tried installing it in Engine/Plugins/Marketplace too.

Anyway, if the issue is not widespread among source users then it seems like a line in the doc might be a better solution? Your call :p

**Comment by Altrue** [comment]
Most of my UI is done in Slate. Maybe the inclusion of "Slate" and "SlateCore" in my build.cs (along with "UnrealEd" and "UMG") is the cause of this.

**Comment by Theliraan** [comment]
Have same problem with 4.25.4 from Launcher. But everything is ok on 4.26.0

**Comment by TheHerobrine** [comment]
@Theliraan That's weird, I'll change the loading phase then... Could you c/c your log of engine start just out of curiosity?

**Comment by Theliraan** [comment]
> @Theliraan That's weird, I'll change the loading phase then... Could you c/c your log of engine start just out of curiosity?

It's more interest situation: I can reproduce bug on 4.25.4 only when opening editor from IDE (Development Editor | Win64 | Rider 2020.3.3 | VSCode latest) and only in one project. So my icons are old here and blueprint nodes aren't flat.

Using plugin on engine. 

[WORKS GOOD - 4.25.4 - From launcher - BP Project A.log](https://github.com/TheHerobrine/DarkerNodes/files/5777624/WORKS.GOOD.-.4.25.4.-.From.launcher.-.BP.Project.A.log)
[WORKS GOOD - 4.26.0 - From launcher - BP Project A.log](https://github.com/TheHerobrine/DarkerNodes/files/5777625/WORKS.GOOD.-.4.26.0.-.From.launcher.-.BP.Project.A.log)

[WORKS BAD - 4.25.4 - From IDE - CPP Project B.log](https://github.com/TheHerobrine/DarkerNodes/files/5777629/WORKS.BAD.-.4.25.4.-.From.IDE.-.CPP.Project.B.log)

[WORKS GOOD - 4.25.4 - From IDE - CPP Project C.log](https://github.com/TheHerobrine/DarkerNodes/files/5777631/WORKS.GOOD.-.4.25.4.-.From.IDE.-.CPP.Project.C.log)
[WORKS GOOD - 4.25.4 - From launcher - CPP Project C.log](https://github.com/TheHerobrine/DarkerNodes/files/5777632/WORKS.GOOD.-.4.25.4.-.From.launcher.-.CPP.Project.C.log)
[WORKS GOOD - 4.26.0 - From IDE - CPP Project C.log](https://github.com/TheHerobrine/DarkerNodes/files/5777633/WORKS.GOOD.-.4.26.0.-.From.IDE.-.CPP.Project.C.log)
[WORKS GOOD - 4.26.0 - From launcher - CPP Project C.log](https://github.com/TheHerobrine/DarkerNodes/files/5777634/WORKS.GOOD.-.4.26.0.-.From.launcher.-.CPP.Project.C.log)

**Comment by TheHerobrine** [comment]
Maybe something overwrite DarkerNodes modification by resetting the style of the editor, but I find it really weird...

If it were a plugin, it will be among those:
```
LogPluginManager: Mounting plugin ApexDestruction
LogPluginManager: Mounting plugin GameplayAbilities
LogPluginManager: Mounting plugin EasyMultiSave
LogPluginManager: Mounting plugin ElectronicNodes
LogPluginManager: Mounting plugin FMODStudio
LogPluginManager: Mounting plugin LDAssistant
LogPluginManager: Mounting plugin LogViewerPro
LogPluginManager: Mounting plugin Substance
```

But I don't think so... Changing the `LoadingPhase` to `PostEngineInit` does solve the problem? If it is, I'll just update this on the next version 😉

**Comment by TheHerobrine** [comment]
Just to be sure, you do have the 1.6 version of Darker Nodes?

**Comment by Theliraan** [comment]
> And just to be sure, you do have the 1.6 version of Darker Nodes?

Yes, it's 1.6. Changing ```LoadingPhase``` from ```Default``` to ```PostEngineInit``` helps, thanks so much. Do I need provide some additional information?

**Comment by TheHerobrine** [comment]
@Theliraan That would be awesome if you could try with `PostDefault` too! I'd prefer that option over `PostEngineInit`.

**Comment by Theliraan** [comment]
> @Theliraan That would be awesome if you could try with `PostDefault` too! I'd prefer that option over `PostEngineInit`.

```PostDefault``` also works as correct as ```PostEngineInit```. Screenshots with ```Default``` vs```PostDefault```:

![image](https://user-images.githubusercontent.com/3195612/103820078-b4895d00-507c-11eb-92ce-85f1e7ca95eb.png)
![image](https://user-images.githubusercontent.com/3195612/103820058-a8050480-507c-11eb-9cc3-6f1afb205833.png)
