### ISSUE TITLE
Some icon still result old-styled

### ISSUE THREAD

**Issue by Giakkons** [TheHerobrine/DarkerNodes#54]
In material editor, static mesh editor and skeletal mesh editor some icons are missing and are still the default ones, resulting in a mixed syle.

![immagine](https://user-images.githubusercontent.com/29116449/103245958-16054980-4962-11eb-8dbb-7fd584dd64c2.png)
![immagine](https://user-images.githubusercontent.com/29116449/103245984-2ae1dd00-4962-11eb-8cde-cd0499d4a962.png)
![immagine](https://user-images.githubusercontent.com/29116449/103246047-5d8bd580-4962-11eb-9b84-acbd474fd486.png)

**Comment by TheHerobrine** [comment]
Thank you for the list! They'll be changed in January 😉

**Comment by TheHerobrine** [comment]
cf https://github.com/TheHerobrine/DarkerNodes/issues/43

**Comment by TheHerobrine** [comment]
Fixed with https://github.com/TheHerobrine/DarkerNodes/issues/43!
