### ISSUE TITLE
Curve editor background and handles results flat white

### ISSUE THREAD

**Issue by Giakkons** [TheHerobrine/DarkerNodes#55]
![immagine](https://user-images.githubusercontent.com/29116449/103297803-5532a980-49f9-11eb-9722-c8b9256b898a.png)
Curve editor background and handles results flat white, making it excessively bright and hard to manage

**Comment by TheHerobrine** [comment]
@Giakkons Hum, this should be fixed in the last version with this https://github.com/TheHerobrine/DarkerNodes/issues/38 🤔...

What version are you using?

**Comment by Giakkons** [comment]
4.25

**Comment by TheHerobrine** [comment]
I meant, what version of the plugin 😛

**Comment by Giakkons** [comment]
> 
> 
> I meant, what version of the plugin 😛

Seem 1.4, guess there's a new version out. Sadly there are no notifications from Epic when an update is pushed :(

**Comment by TheHerobrine** [comment]
Yes, the 1.5 should be available for almost a week 😕...

**Comment by Giakkons** [comment]
Sadly i do not use the launcher enough and Epic do not notify for updates on installed elements. Updating the plugin fixed the curve but screwd the colors tho, now everything is way darker :(

**Comment by TheHerobrine** [comment]
@Giakkons Hum, 1.5 also fix the color update, so they won't change after you updated it (https://github.com/TheHerobrine/DarkerNodes/issues/39)
