### ISSUE TITLE
Selected actor text hard to read with dark text on dark background

### ISSUE THREAD

**Issue by KohiZoey** [TheHerobrine/DarkerNodes#57]
Whichever actor is selected in the world outliner seems to have black text on a dark background making it difficult to read:

![darker_nodes_world_outliner_selected_actor](https://user-images.githubusercontent.com/1184807/103467291-84e7f700-4d02-11eb-9175-c7237bb53d28.png)

It seems to be the same case inside the details window showing the current actor, although a bit more legible in this case:

![darker_nodes_details_actor_name](https://user-images.githubusercontent.com/1184807/103467290-7e597f80-4d02-11eb-9a83-3f9128309424.png)

Maybe with the darker selected background, the text could be brighter (or just white)?

**Comment by TheHerobrine** [comment]
@KohiZoey Try restarting your editor, this should fix it! (The selection color takes 2 restart to be correctly set)

**Comment by TheHerobrine** [comment]
> Maybe with the darker selected background, the text could be brighter (or just white)?

Also, to answer your suggestion, the selected text color id hard coded black, so there's no way I can change it yet 😕...

**Comment by KohiZoey** [comment]
I see now, I was able to restart and the selection colors make more sense now, thanks!
