### ISSUE TITLE
Difficult to read keyboard shortcuts in Editor Preferences

### ISSUE THREAD

**Issue by KohiZoey** [TheHerobrine/DarkerNodes#58]
In Editor Preferences > Keyboard Shortcuts, it seems like the input text fields have a light gray text on top of a white background making it very difficult to read.

![darker_nodes_preferences_keyboard_shortcuts](https://user-images.githubusercontent.com/1184807/103489444-79133800-4dc9-11eb-98f2-a5a42daa312b.png)

Speaking out of my depth here as a newbie to UE4, but I'm guessing the text fields that capture keystrokes are a different class than text fields that strictly capture text?

**Comment by TheHerobrine** [comment]
Well spotted, I'll fix this for the 1.7! (should be available in a week I guess)

> Speaking out of my depth here as a newbie to UE4, but I'm guessing the text fields that capture keystrokes are a different class than text fields that strictly capture text?

Yes, that's probably another text field type 🤔

**Comment by TheHerobrine** [comment]
Fixed! Will be available in 1.7 😉

![image](https://user-images.githubusercontent.com/4563971/103772613-179dd400-502a-11eb-9fef-3a7d1d3a1b0e.png)
