### ISSUE TITLE
Add a series of solid icons

### ISSUE THREAD

**Issue by TheHerobrine** [TheHerobrine/DarkerNodes#6]
Some people might prefer solid icons (instead of thin), so I could make a series with solid icons (and maybe duotone icons too)

**Comment by TheHerobrine** [comment]
I don't know if people really want them, that's a lot of work (+ making it in small icons).
I'm waiting for people feedback to do this.

**Comment by deanvaessen** [comment]
Seems like it would mesh well with https://github.com/TheHerobrine/DarkerNodes/issues/41
Solid, flat icons with some colour would help with legibility for the small icons, though generally I'm a fan of some colour and if I was working with the large icons I'd enable them as well. 

+1 from me :)

**Comment by Xpert0** [comment]
Sounds good to me

**Comment by TheHerobrine** [comment]
I'm on it!
![image](https://user-images.githubusercontent.com/4563971/105614365-38577f00-5dc9-11eb-818b-ba4f487fe13a.png)

**Comment by TheHerobrine** [comment]
Pfew, made it all...

![image](https://user-images.githubusercontent.com/4563971/105615621-71e0b800-5dd2-11eb-97e4-9f306516e878.png)

I'll do the small version in another update...

**Comment by TheHerobrine** [comment]
New look:
![image](https://user-images.githubusercontent.com/4563971/105616014-05ff4f00-5dd4-11eb-8b26-ce9a2cae5e8a.png)

I'm marking this as experimental because it's missing the small icons, but other than that it's ready!

**Comment by deanvaessen** [comment]
Sick! Would it be possible for us to set colours on each individual icon? Maybe just an overlay.

**Comment by TheHerobrine** [comment]
@deanvaessen I've added an option to make colored by group, but you'd prefer to manually choose the color for each icon 🤔 ?
cf https://github.com/TheHerobrine/DarkerNodes/issues/108

Out of curiosity, what do you plan to do? Maybe I could make it a bit easier...

**Comment by deanvaessen** [comment]
> Out of curiosity, what do you plan to do? Maybe I could make it a bit easier...

Just would like to make it easier at a glance to pick out the individual icons. Make the save button a distinct colour, the play button, etc. The new icons are really nice, but having everything grey mushes them together a bit.
