### ISSUE TITLE
Stretched icons

### ISSUE THREAD

**Issue by TheHerobrine** [TheHerobrine/DarkerNodes#60]
There seems to have some stretched icons, but I cannot find where...

![image](https://user-images.githubusercontent.com/4563971/103686140-a52be600-4f8e-11eb-86ef-3c2be215baf9.png)

EDIT: Appear's it's on World Settings

![image](https://user-images.githubusercontent.com/4563971/103765012-c89d7200-501c-11eb-9c1a-ad8755caca42.png)

**Comment by stardast132** [comment]
i havent seen them, where are they?

**Comment by TheHerobrine** [comment]
Neither did I, but someone reported this on the question page:
https://www.unrealengine.com/marketplace/en-US/product/darker-nodes/questions

I asked him to give a bit more detail, hope he'll see my message 😕

**Comment by TheHerobrine** [comment]
It seems to be affected by the button padding option in `Editor Preferences/Darker Nodes/Theme`. Hope to be able to fix this without remove this feature...

**Comment by TheHerobrine** [comment]
Ok, this was pretty complicated to fix, but I developed a super cool solution that I though would be reserved for v2.0.

So maybe the next version of DarkerNodes will be 2.0, with a ton of customization 🥳 ! This will be **HUGE**.

**Comment by TheHerobrine** [comment]
This doesn't look like much, but I can assure you, this needed awesome changes to Darker Nodes!
![image](https://user-images.githubusercontent.com/4563971/103938326-5adf6c00-512a-11eb-93ed-a0f443e47cea.png)

**Comment by CrownKing2499** [comment]
The new update looks pretty hot! When will it be released?

**Comment by TheHerobrine** [comment]
@CrownKing2499 It's released, but don't download the update just now, there's a critical bug that make the editor crash 😢...
https://github.com/TheHerobrine/DarkerNodes/issues/73
