### ISSUE TITLE
World Outliner Color customization

### ISSUE THREAD

**Issue by yorschor** [TheHerobrine/DarkerNodes#64]
Hi.
I played around with your plugin a bit but cant find any way to change to color of the World Outliner. Am I missing something? And if not would it be possible to include such an option to make this possible? 
Thanks!

**Comment by TheHerobrine** [comment]
@yorschor Hum, this may be the "Primary Color" that you can find here:

![image](https://user-images.githubusercontent.com/4563971/103890901-2bf4d600-50e9-11eb-9399-372432d47f90.png)

Prefer the `Primary Color` over the `Custom Primary Color` if possible.
Also, be warned that the Primary Color needs TWO restarts of the editor to be correctly set!

---

If I did not understand correctly what you meant by "World Outliner", could you please point me to what you had in mind?

**Comment by yorschor** [comment]
Hi. 
I am afraid the primary color cant be what I am looking for since its orange ^^
I am talking about the background color of this  
![Screenshot 2021-01-07 143619](https://user-images.githubusercontent.com/25516638/103898858-db37aa00-50f5-11eb-9a2f-5df7ee4f1d18.png)

**Comment by yorschor** [comment]
Nice thank you very much ^^

**Comment by TheHerobrine** [comment]
Done, this will take the "GreyBase" color like this 😉

![image](https://user-images.githubusercontent.com/4563971/104029339-26bb8800-51ca-11eb-83a3-5bc749c58e26.png)

**Comment by yorschor** [comment]
yeee. looks nice :D
