### ISSUE TITLE
[BUG] With Use Small Tool Bar Icon 

### ISSUE THREAD

**Issue by FAKlR** [TheHerobrine/DarkerNodes#67]
If you enable Use Small Tool Bar Icons in the editior preferences , it create white hole on the top of the main unreal window .

![image](https://user-images.githubusercontent.com/20428419/103964695-58960580-515c-11eb-91ca-e15c6c314565.png)

**Comment by TheHerobrine** [comment]
@FAKlR Yes, because modifying this option trigger an overwrite of Darker Nodes theme. Just restart the editor and it will fix itself 😉
