### ISSUE TITLE
Localization Dashboard - The Translation Editor Window needs some work

### ISSUE THREAD

**Issue by Altrue** [TheHerobrine/DarkerNodes#69]
In the Localization Dashboard, the Translation Editor Window, which enables devs to contribute to an alternate localization of the game, is still using white backgrounds for white fonts in some places.

![TranslationEditorWindow](https://user-images.githubusercontent.com/9656008/104048314-50cd7400-51e3-11eb-8122-309697142905.png)

**Comment by TheHerobrine** [comment]
@Altrue Seems like it's already fixed, probably by https://github.com/TheHerobrine/DarkerNodes/issues/52:
![image](https://user-images.githubusercontent.com/4563971/104053308-4616dd00-51eb-11eb-82ed-6a9ca06904a8.png)

Are you using the 1.6 version of the plugin 🤔 ?

**Comment by Altrue** [comment]
Ah, my apologies! I'm one plugin version late! You work too fast 👍
