### ISSUE TITLE
Ability to change fonts

### ISSUE THREAD

**Issue by TheHerobrine** [TheHerobrine/DarkerNodes#70]
Some people would like to change the default Roboto font

**Comment by TheMrBigWill** [comment]
yep thats me

**Comment by TheHerobrine** [comment]
Managed to make it work 🥳 ! There will be 10 Fonts under OFL licence included 😉

**Comment by TheHerobrine** [comment]
You'll also be able to provide your own ttf fonts:
![image](https://user-images.githubusercontent.com/4563971/104326405-005b5c80-54ea-11eb-906f-91e113d432b2.png)

**Comment by Gliptal** [comment]
Would it be possible to add an option to change the Message Log font?

**Comment by hugoattal** [comment]
@Gliptal This wasn't possible when I did this update since it was hard-coded (IIRC). But since I discovered a way to update some hard-coded stuff in Electronic Nodes, I'll see if this isn't possible in Darker Nodes for the fonts.
