### ISSUE TITLE
Menu bar on "Pick Parent Class" window is incorrect

### ISSUE THREAD

**Issue by W2Wizard** [TheHerobrine/DarkerNodes#75]
**Issue:**
When you create a new actor class you can notice that the top right corner of the menu bar the X Icon is stretched as well having additional backgrounds for the non-existent minimize and maximize buttons.

**Image:**
![image](https://user-images.githubusercontent.com/63303990/104109821-f65f1100-52d1-11eb-83fb-956163859225.png)

**Comment by TheHerobrine** [comment]
Thank you for spotting this, it should be fairly easy to solve this 🤔

**Comment by TheHerobrine** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/4563971/104329667-701f1680-54ed-11eb-99dc-23f0227a4215.png)

**Comment by W2Wizard** [comment]
Beautiful ! 👏
