### ISSUE TITLE
Transform sliders and axis icons have spacing issues

### ISSUE THREAD

**Issue by W2Wizard** [TheHerobrine/DarkerNodes#76]
**Issue:**
So the sliders work fine however the axis labels are slightly larger than the body of the slider and also seems to get a border when clicked on?

**Video:**

https://user-images.githubusercontent.com/63303990/104110216-cb76bc00-52d5-11eb-9b54-1872b2a6dac7.mp4

**Comment by W2Wizard** [comment]
Also setting the button padding to big only affects the middle row

![image](https://user-images.githubusercontent.com/63303990/104110300-b9e1e400-52d6-11eb-8b90-7719404c0756.png)

**Comment by TheHerobrine** [comment]
I may have forgotten a padding for some specific numeral values (of "Location" and "Scale") 🤔... I'll investigate...

It also has to do with how the editor draw those boxes, it actually is a box with a box. I'll see if it's possible to make it a bit more polished 😉

**Comment by TheHerobrine** [comment]
Ok, so the size of the slider is actually the same as the default:
![image](https://user-images.githubusercontent.com/4563971/104215978-c6cb1880-5439-11eb-9a60-e3da6ab4b7ba.png)

I fixed the dimension issue:
![image](https://user-images.githubusercontent.com/4563971/104216579-87e99280-543a-11eb-9f99-1772d91ceeb0.png)

And I'll fix the stretch lock icon.

**Comment by TheHerobrine** [comment]
Done!
![image](https://user-images.githubusercontent.com/4563971/104247530-44a61880-5468-11eb-8ccd-b29822c18054.png)
