### ISSUE TITLE
Styling for all inputs seem to be missing

### ISSUE THREAD

**Issue by KohiZoey** [TheHerobrine/DarkerNodes#79]
It looks like the styling for the buttons and inputs is missing which makes it a lot harder to look at and work with.

I'm using UE 4.26.0 and the plugin version 2.2 from Marketplace. So far, I've tried restarting a couple of times, starting with a brand new project with default settings.

![darker_nodes_missing_button_details](https://user-images.githubusercontent.com/1184807/104110888-e4a94980-5290-11eb-89a0-244ced0d7608.png)

**Comment by TheHerobrine** [comment]
@KohiZoey That's weird, sorry for this, it shouldn't look like this...
![image](https://user-images.githubusercontent.com/4563971/104111279-7db38100-52e0-11eb-94f1-d032bfef6d09.png)

That weir that you have the right background for the "Mobility" buttons, but not the others...

Could you screen me your Darker Nodes settings?
Could you try deleting the plugin and redownload it?

**Comment by KohiZoey** [comment]
I also had tried uninstalling and re-installing the plugin a couple of times to no avail, however it *seems* to have gone away after the following steps:

- Click "Reload texture resources" (not sure if this actually did anything or not)
- Turn off "Master Activation" and click "Reload default"
- Restart the editor
- Turn back on "Master Activation"

I guess it isn't a bug or anything to be fixed, just a bumpy upgrade process with Marketplace :)

**Comment by TheHerobrine** [comment]
@KohiZoey Well, I hope not everyone will have this 😅...

- The "Reload texture resources" is more for me than for end-users, there's little change it has to do with the fix, it's already triggered during the loading of the plugin.
- The "Reload default style" just reset the default editor style setting, nothing too fancy.

Anyway, thank you very much for those informations! I'll keep this issue open if any other user encounter such a problem!

**Comment by TheHerobrine** [comment]
Seems like another user have the same problem 😕 https://github.com/TheHerobrine/DarkerNodes/issues/82
I need to find out why the button shader are not working/compiled when updating from previous Darker Nodes version...

**Comment by TheHerobrine** [comment]
Ok, the solution given by Zoey worked partially for Dean, so after a quick call, here's what solved the problem:
- In the content browser, activate Plugin Content
![image](https://user-images.githubusercontent.com/4563971/104189498-0a625a00-541b-11eb-873d-bd5646dde374.png)
- Go into the DarkerNodes Content/Materials folder
![image](https://user-images.githubusercontent.com/4563971/104189593-2cf47300-541b-11eb-95c1-bdfdca6d70e7.png)
- On each missing material (if you don't know, just do it for all of them):
  - Open the material
  - Move a random node
  - Apply and then save
![image](https://user-images.githubusercontent.com/4563971/104189696-4eedf580-541b-11eb-8c1c-192b9787747c.png)

It's weird that people have to do that though... My guess is that it may come for the fact that they updated 2.2 from 2.1 or 2.0 which was buggy, but I don't know why 🤔...

I'll this open just to be sure it does not concern everyone 😅

**Comment by TheHerobrine** [comment]
I think I found a definitive answer to this bug, it should be available in 2.4 🤔

**Comment by TheHerobrine** [comment]
I think I might have fixed this by forcing recompilation of those shaders 🥳 !
![image](https://user-images.githubusercontent.com/4563971/104747048-516c8a00-5750-11eb-871a-4a3daee00304.png)

**Comment by TheHerobrine** [comment]
Ok, to fix this thing, you'll just have to tick this box:
![image](https://user-images.githubusercontent.com/4563971/104752786-6862aa80-5757-11eb-88c0-5f664b80d824.png)

This should auto-fire the first time you open a project with Darker Nodes.
