### ISSUE TITLE
Checkboxes for UMG are now just boxes

### ISSUE THREAD

**Issue by W2Wizard** [TheHerobrine/DarkerNodes#80]
**Issue:**
When using a checkbox in UMG it just ends up being a box, it still works however it lost its visual feedback pretty much.

Changing the state to undetermined restores it however just for that state.

**Image:**
![image](https://user-images.githubusercontent.com/63303990/104119206-3c49c280-532e-11eb-9652-db98bed4989e.png)

**Comment by W2Wizard** [comment]
This seems to be a similar issue with the slider images

![image](https://user-images.githubusercontent.com/63303990/104119643-09ed9480-5331-11eb-9ccf-212af2a62418.png)

**Comment by TheHerobrine** [comment]
@W2Wizard That weird... It looks like https://github.com/TheHerobrine/DarkerNodes/issues/79, but weirder...

What version of Unreal Engine are you using?
What version of Darker Nodes are you using?

You may want to try those steps:

- Go to the settings of the plugin and then
- Turn off "Master activation"
- Click on "Reload default"
- Restart the Editor
- Tun on "Master activation"
 -Restart the editor

**Comment by TheHerobrine** [comment]
Oh no, it seems to be different, I think I found where it comes from!

**Comment by TheHerobrine** [comment]
Love reading this in the engine code 😂
![image](https://user-images.githubusercontent.com/4563971/104182123-4217d480-5410-11eb-86a0-07d93320b8d4.png)

**Comment by W2Wizard** [comment]
Code projects be like:

`// THIS SHOULD NEVER BE DONE LIKE THIS, THIS IS CATASTROPHICALLY BAD REMOVE BEFORE RELEASE!!1!!`

*Still gets shipped with the same code 6 years later*

**Comment by TheHerobrine** [comment]
Wow, after a lonnnng time, I found a hack to fix their hack 😛
