### ISSUE TITLE
Missing button highlight outlines

### ISSUE THREAD

**Issue by deanvaessen** [TheHerobrine/DarkerNodes#81]
There is no more visual feedback (button outline) on snackbars when hovering over them, such as the "open previously opened windows on crash" and "restart required":

https://user-images.githubusercontent.com/13887261/104168463-636fc500-53fe-11eb-8d72-8e13abbd5d09.mp4

**Comment by TheHerobrine** [comment]
Duplicate of https://github.com/TheHerobrine/DarkerNodes/issues/82 (it's the same bug, button shaders not rendering)

**Comment by TheHerobrine** [comment]
This was a duplicate of #82 😉
