### ISSUE TITLE
Missing button backgrounds

### ISSUE THREAD

**Issue by deanvaessen** [TheHerobrine/DarkerNodes#82]
![image](https://user-images.githubusercontent.com/13887261/104168919-12140580-53ff-11eb-97d0-ad8e3e3bf5dd.png)
![image](https://user-images.githubusercontent.com/13887261/104168995-2b1cb680-53ff-11eb-89ce-e40b751022b8.png)

**Comment by TheHerobrine** [comment]
Seems like your bugs is the same as this one: https://github.com/TheHerobrine/DarkerNodes/issues/79

Could you try the following steps and tell me what worked (if any)?

- If you have some shaders compiling, could you wait for them to finish and relaunch the editor?
- Could you go to the settings of the plugin and then
  - Turn off "Master activation"
  - Click on "Reload default"
  - Restart the Editor
  - Tun on "Master activation"
  - Restart the editor

**Comment by deanvaessen** [comment]
Went through the steps, fixed *some* of them, but not all of them:
![image](https://user-images.githubusercontent.com/13887261/104182224-6e335580-5410-11eb-9428-60ddf6f6881a.png)

**Comment by TheHerobrine** [comment]
I'll close this once since it's resolved and put the solution on the other issue: https://github.com/TheHerobrine/DarkerNodes/issues/79
