### ISSUE TITLE
Blueprint variable type context menu doesn't refresh causing text overdrawing issues

### ISSUE THREAD

**Issue by symon23** [TheHerobrine/DarkerNodes#85]
Hi, 

I have just purchased your plugin and it looks lovely, however, I am facing what I believe has to be a bug.
When I try to change a variable type in a blueprint the context menu that lets you choose the type seems to have some refreshing issues, as I try to look up the new type the view doesn't seem to refresh and you get lots of text overdrawing.

This is a gif to show you what I am talking about:
https://gyazo.com/935628b38f62597b825fe922bf897f9a

For now unfortunately the plugin is basically unusable as I can't even look up the variable types.

**Comment by TheHerobrine** [comment]
Sorry for this I admit, I have no idea what can cause such a bug 😕... Is it only on this menu? Does the right-click menu on blueprint do the same thing?

That could potentially come from a known issue though, could you try the steps described in this post: https://github.com/TheHerobrine/DarkerNodes/issues/79#issuecomment-757959890, and tell me if that fixes it?

**Comment by symon23** [comment]
Hi, sorry I had completely forgotten about providing the engine version.

This is happening on 4.25
The plugin version is 2.3

I confirm this doesn't happen with the right click menu in blueprints.

I will try the solution described in #79 comment and let you know how it goes.

**Comment by symon23** [comment]
So following the solution you have given at the bottom of the #79 comment solved the issues I was having and actually also solved the missing button background issue I was also experiencing but didn't even notice. Thanks for the support.

**Comment by TheHerobrine** [comment]
Should be fixed in the next version: https://github.com/TheHerobrine/DarkerNodes/issues/79#issuecomment-761045548
