### ISSUE TITLE
Missing color in Sequencer

### ISSUE THREAD

**Issue by zjrl** [TheHerobrine/DarkerNodes#87]
hi

https://user-images.githubusercontent.com/69996552/104401093-7addb800-558e-11eb-8b2d-b38fc09b144b.mp4

**Comment by TheHerobrine** [comment]
Ok, I believe the bug is the missing color of this bar:
![image](https://user-images.githubusercontent.com/4563971/104446389-ab2b5380-559a-11eb-8580-3e52aa06a113.png)

I'll fix this in the next update 😉

**Comment by TheHerobrine** [comment]
Fixed, will be available in 2.4!
![image](https://user-images.githubusercontent.com/4563971/104756458-225c1580-575c-11eb-959e-7103d9e625a1.png)
