### ISSUE TITLE
Niagara float sliders are still white, makes the numbers hard to read

### ISSUE THREAD

**Issue by InvertedGames-Dev** [TheHerobrine/DarkerNodes#9]
The float boxes in niagara are still white, which makes the numbers hard to read. 

Here's what they look like:
![image](https://user-images.githubusercontent.com/32015329/102153948-4233bb80-3ec8-11eb-8fbb-bd1ded5b3fbf.png)

I'm guessing they should be black like the vector boxes here:
![image](https://user-images.githubusercontent.com/32015329/102154042-81faa300-3ec8-11eb-8772-5f97cbe02fd4.png)

**Comment by TheHerobrine** [comment]
Fixed, ready for 1.1!

![image](https://user-images.githubusercontent.com/4563971/102247393-3237ce00-3f00-11eb-9b2e-776dfba08c45.png)

**Comment by TheHerobrine** [comment]
Available. If you're on 4.26, wait for the 1.2 update (I let a debug thing on the 4.26 1.1 update... cf https://github.com/TheHerobrine/DarkerNodes/issues/21)
