### ISSUE TITLE
Missing roboto default fonts?

### ISSUE THREAD

**Issue by Thovex** [TheHerobrine/DarkerNodes#90]
Hey!

I think I'm missing the roboto default fonts? If I switch from fonts it will stick to the previous selected font.
![image](https://user-images.githubusercontent.com/9029361/104608046-cae97700-5681-11eb-9e96-d959d462dcd8.png)

**Comment by TheHerobrine** [comment]
@Thovex Selecting the Roboto font actually select the default font of the engine (and don't modify anything). You'll need a restart to get it.

I'll probably change the behavior of that to reload the default font 🤔

**Comment by Thovex** [comment]
Oh, lol, I was missing the 'bold' part of the font when I downloaded the new update (didn't touch the font part), so I added the roboto bold font to the project and linked it to that.

**Comment by TheHerobrine** [comment]
@Thovex You don't need to, if you want to keep the default font (Roboto), just select it and restart the editor 😉
