### ISSUE TITLE
Graph Nodes Texture Alignment

### ISSUE THREAD

**Issue by FanaticNinja** [TheHerobrine/DarkerNodes#91]
![unknown](https://user-images.githubusercontent.com/3609319/104631028-e3916700-5658-11eb-9252-80482b028ddc.png)

Fresh install on 4.24. Tried changing a bunch of theme settings to see if it would fix, but no luck.

**Comment by TheHerobrine** [comment]
Ok, I managed to reproduce. It appears to be specific on 4.24 engine version (there's no problem with 4.25 and 4.26 engine version).

I'll investigate this...

**Comment by TheHerobrine** [comment]
Seems like there's already a bug in the default blueprint theme, only it's not very visible 😛
![image](https://user-images.githubusercontent.com/4563971/104761627-76b6c380-5763-11eb-9572-37bf328107e6.png)

**Comment by TheHerobrine** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/4563971/104762603-ed07f580-5764-11eb-800f-4f43fd4dfd31.png)

**Comment by FanaticNinja** [comment]
Awesome! Thanks so much.
