### ISSUE TITLE
Text Glicth While Searching for the Parent Class

### ISSUE THREAD

**Issue by raijoking** [TheHerobrine/DarkerNodes#93]
![3](https://user-images.githubusercontent.com/21275721/104672978-c5406f80-571b-11eb-87be-8dfce160816e.png)
This is a Plug-in breaker Glitch Proof

**Comment by TheHerobrine** [comment]
Arg, this tend to happen way to often 😞... It's the same bug as https://github.com/TheHerobrine/DarkerNodes/issues/85.
Here's the fix: https://github.com/TheHerobrine/DarkerNodes/issues/79#issuecomment-757959890

Really sorry for that...

If you have time, could you please send me the content of `UE_4.26\Engine\Plugins\Marketplace\DarkerNodes\Content\Materials` **before** AND **after** the manipulation?

**Comment by TheHerobrine** [comment]
Should be fixed in the next version: https://github.com/TheHerobrine/DarkerNodes/issues/79#issuecomment-761045548
